%% test_heightmap_raster.m
% Verify direct height-map raster output does not emit contour fragments.
% Run from the project root: run('tests/test_heightmap_raster.m')

addpath(fullfile(fileparts(mfilename('fullpath')), '..', 'core'));

fprintf('\n=== test_heightmap_raster ===\n');

height = ones(3, 3);  % source units
[segments, info] = heightmap_to_segments(height, ...
    'SourcePitch', 1, ...
    'TargetMaxXY', 0.003, ...
    'HatchPitch_mm', 0.001, ...
    'LayerHeight_mm', 0.001, ...
    'StageZConvention', true, ...
    'WoodpileMode', true, ...
    'Serpentine', true, ...
    'CoordMode', 'edges');

assert(info.LayerCount == 1, 'Expected one layer.');
assert(size(segments, 1) == 3, 'Expected one full-width segment per scanline.');

expected = [
    0.000 0.0005 -0.0005 0.003 0.0005 -0.0005
    0.003 0.0015 -0.0005 0.000 0.0015 -0.0005
    0.000 0.0025 -0.0005 0.003 0.0025 -0.0005
];

assert(max(abs(segments(:) - expected(:))) < 1e-12, ...
    'Height-map raster output does not match expected full-width serpentine rows.');

fprintf('  PASS: full-height map exports clean full-width serpentine scanlines.\n');

baseOnly = zeros(2, 2);
[baseSegments, baseInfo] = heightmap_to_segments(baseOnly, ...
    'SourcePitch', 1, ...
    'TargetMaxXY', 0.002, ...
    'BaseHeight', 0.5, ...
    'HatchPitch_mm', 0.001, ...
    'LayerHeight_mm', 0.0005, ...
    'StageZConvention', true, ...
    'WoodpileMode', true, ...
    'Serpentine', true, ...
    'CoordMode', 'edges');

expectedBase = [
    0.000 0.0005 -0.00025 0.002 0.0005 -0.00025
    0.002 0.0015 -0.00025 0.000 0.0015 -0.00025
];

assert(baseInfo.LayerCount == 1, 'Expected one base-only layer.');
assert(abs(baseInfo.BaseHeight_mm - 0.0005) < 1e-12, ...
    'Source-unit base height was not scaled to mm correctly.');
assert(max(abs(baseSegments(:) - expectedBase(:))) < 1e-12, ...
    'Base-only raster output does not match expected support scanlines.');

fprintf('  PASS: BaseHeight adds a full support layer in the raster function.\n');

[positiveBaseSegments, positiveBaseInfo] = heightmap_to_segments(baseOnly, ...
    'SourcePitch', 1, ...
    'TargetMaxXY', 0.002, ...
    'BaseHeight', 0.5, ...
    'HatchPitch_mm', 0.001, ...
    'LayerHeight_mm', 0.0005, ...
    'StageZConvention', false, ...
    'WoodpileMode', true, ...
    'Serpentine', true, ...
    'CoordMode', 'edges');

assert(positiveBaseInfo.LayerCount == 1, 'Expected one positive-Z base layer.');
positiveZ = positiveBaseSegments(:, [3 6]);
assert(max(abs(positiveZ(:) - 0.00025)) < 1e-12, ...
    'StageZConvention=false should output positive Z values.');

fprintf('  PASS: StageZConvention=false outputs positive Z values.\n');
fprintf('\n=== test_heightmap_raster complete ===\n\n');
